MessageBoard/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 resources :messages do 
 	resources :comments
 end
 root 'messages#index'
end

MessageBoard/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MessageBoard/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

MessageBoard/app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	has_many :comments
end

MessageBoard/app/models/user.rb
class User < ApplicationRecord
	has_many :messages
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

MessageBoard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

MessageBoard/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :find_message
	before_action :find_comment, only: [:edit, :update, :destroy]
	before_action :authenticate_user!
	def create
		# @message = Message.find(params[:message_id])
		@comment = @message.comments.create(comment_params)

		@comment.user_id = current_user.id

		if @comment.save
			redirect_to message_path(@message)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to message_path(@message)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to message_path(@message)
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def find_message
		@message = Message.find(params[:message_id])
	end

	def find_comment
		@comment = @message.comments.find(params[:id])
	end


end

MessageBoard/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	before_action :find_message, only:[:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@messages=Message.all.order("created_at DESC")
	end

	def show
		
	end
	def new
		@message= current_user.messages.build
	end

	def create
		@message=current_user.messages.build(message_params)
		if @message.save
			redirect_to root_path
		else 
			render 'new'
		end
	end

	def edit	
	end

	def update
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end

	def destroy
		@message.destroy
		redirect_to root_path
	end


	private

		def message_params
			params.require(:message).permit(:title, :description)
		end

		def find_message
			@message= Message.find(params[:id])
		end
end

MessageBoard/app/helpers/application_helper.rb
module ApplicationHelper
end

MessageBoard/app/helpers/comments_helper.rb
module CommentsHelper
end

MessageBoard/app/helpers/messages_helper.rb
module MessagesHelper
end

MessageBoard/app/views/comments/_comment.html.erb
<div class="comment">
	
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-posted-by">Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

	<div class="links">
		<% if user_signed_in? %>
			<% if comment.user_id== current_user.id %>
			<%= link_to "Edit", edit_message_comment_path(comment.message, comment) %>
			<%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Are you sure?" } %>
			<% end %>
		<% end %>
		<p><%=  %></p>

	</div>	
</div>

MessageBoard/app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build])  do |f| %>
  <%= f.input :content, label:"Comment" %>
  <%= f.button :submit, :class => 'btn-custom' %>
<% end %>

MessageBoard/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@message, @comment]) do |f| %>
	<%= f.input :content, label: "Comment" %>
	<%= f.button :submit %>
<% end %>

MessageBoard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBoard</title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
     <%= csrf_meta_tags %>
  </head>

  <body>
   	
   	<nav class="navbar navbar-light" style="background-color: #262626; >
		<div class="container">
			<div class="navbar-header">
				<%= link_to "My Message Board", root_path, class: "navbar-brand" %>
			</div>
			<ul class="navbar-nav nav" style="margin-left: 250px;">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>	
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>
			<% if user_signed_in? %>
				<p style="margin-right: 50px;"><%= link_to "New Message", new_message_path, class: "navbar-text navbar-link navbar-right" %></p>
			<% end %>
		</div>
	</nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
    	<%= yield %>
    </div>
     

  </body>
</html>

MessageBoard/app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label:"Message Title" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

MessageBoard/app/views/messages/edit.html.erb
<h1>Edit Message</h1>
<%= render 'form' %>

MessageBoard/app/views/messages/index.html.erb
<% @messages.each do |message| %>
<div class="col-md-4">
		<div class="message">
			<h2 class="message-title"> <%= message.title %></h2>
			 <%= link_to "View Message", message_path(message), class: " btn-main" %>
		</div>
</div>
<% end  %>

MessageBoard/app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<h1>New message</h1>
	<%= render 'form' %>
</div>

MessageBoard/app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<h2><%= @message.title %></h2>
		<p class="message-posted-by">Posted by <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago</p>

		<p class="message-desc"><%= @message.description %></p>



		<h3>Comments:</h3>
		<%= render @message.comments %>

		<h3 class="reply-to-msg">Reply to Message:</h3>
		<%= render 'comments/form' %>

		<div class="links btn-group">
			<%= link_to "Back", root_path, class: "btn btn-default" %>
			<% if user_signed_in? %>

					<% if @message.user_id == current_user.id %>
							<%= link_to "Edit", edit_message_path(@message), class: "btn btn-default" %>
							<%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: 	"Are you sure?" }, class: "btn btn-default" %>
					<% end %>
			<% end %>
		</div>
		
	</div>	
</div>